# AI agent skills

- repo:
    url: https://github.com/philschmid/mcp-cli
    ref: v0.1.3
    with:
      - include: ["SKILL.md"]
      - rename:
          - "SKILL.md": ".claude/skills/mcp-cli/SKILL.md"

- repo:
    url: https://github.com/jmreicha/configs
    ref: main
    with:
      - include: ["skills/research/SKILL.md"]
      - rename:
          - "skills/research/SKILL.md": ".claude/skills/research/SKILL.md"
