version: "2"

linters:
  # Default set of linters.
  # The value can be: `standard`, `all`, `none`, or `fast`.
  default: none

  # Enable specific linters.
  enable:
    - gosec # security checks
    - govet # better 'go vet'
    - revive # better 'golint'
    - staticcheck # unused code
    - errcheck # find unchecked errors

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gofmt
    - gofumpt # better 'go fmt'
    - goimports # import management

issues:
  exclude-rules:
    # Exclude var-naming check for deprecated util package
    - path: internal/cmd/util
      linters:
        - revive
      text: "avoid meaningless package names"
# TODO: lint struct alignment for better memory management
# linters-settings:
# maligned:
# print struct with more effective memory layout or not, false by default
# suggest-new: true
