version: 2

# Project metadata
project_name: cfgctl

# Build configuration
builds:
  - id: cfgctl
    main: ./cmd/cfgctl
    binary: cfgctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

# Archive configuration
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

# Checksum configuration
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# SBOM configuration
sboms:
  - id: archive
    artifacts: archive

# Homebrew tap configuration
homebrew_casks:
  - name: cfgctl
    repository:
      owner: jmreicha
      name: cfgctl
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/jmreicha/cfgctl"
    description: "CLI for managing complex configuration setup"
    binaries:
      - cfgctl
    url:
      verified: "github.com/jmreicha/cfgctl"

# Docker configuration
dockers_v2:
  - id: default
    dockerfile: Dockerfile
    images:
      - "{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - "--pull"
    disable: true

# Changelog configuration
changelog:
  use: github
  sort: asc
  abbrev: 0
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other changes"
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

# GitHub release configuration
release:
  github:
    owner: jmreicha
    name: cfgctl
  draft: false
  prerelease: auto
  mode: append
  name_template: "{{ .Tag }}"
  header: |
    ## Release {{.Version}}

    **Full Changelog**: https://github.com/jmreicha/cfgctl/compare/{{ .PreviousTag }}...{{ .Tag }}
