version: "3"

vars:
  BINARY_NAME: lazycfg
  BUILD_DIR: dist
  GO_VERSION: 1.23.5

tasks:
  default:
    cmds:
      - task --list

  check-tools:
    desc: Check if required CLI tools are installed
    silent: true
    cmds:
      - |
        echo "Checking required tools..."
        MISSING=()
        HAS_BREW=false

        # Check if brew is available
        if command -v brew &> /dev/null; then
          HAS_BREW=true
        fi

        # Check Go
        if ! command -v go &> /dev/null; then
          if [ "$HAS_BREW" = true ]; then
            MISSING+=("go|brew install go")
          else
            MISSING+=("go|https://go.dev/doc/install")
          fi
        else
          echo "✓ go $(go version | awk '{print $3}')"
        fi

        # Check golangci-lint
        if ! command -v golangci-lint &> /dev/null; then
          MISSING+=("golangci-lint|go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest")
        else
          echo "✓ golangci-lint $(golangci-lint version --format=short 2>/dev/null || echo 'installed')"
        fi

        # Check bd (beads)
        if ! command -v bd &> /dev/null; then
          if [ "$HAS_BREW" = true ]; then
            MISSING+=("bd|brew install steveyegge/beads/bd")
          else
            MISSING+=("bd|curl -fsSL https://raw.githubusercontent.com/steveyegge/beads/main/scripts/install.sh | bash")
          fi
        else
          echo "✓ bd $(bd version 2>/dev/null || echo 'installed')"
        fi

        # Check pre-commit
        if ! command -v pre-commit &> /dev/null; then
          if [ "$HAS_BREW" = true ]; then
            MISSING+=("pre-commit|brew install pre-commit")
          else
            MISSING+=("pre-commit|pip install pre-commit (https://pre-commit.com/#install)")
          fi
        else
          echo "✓ pre-commit $(pre-commit --version | awk '{print $2}')"
        fi

        # Check common-repo
        if ! command -v common-repo &> /dev/null; then
          MISSING+=("common-repo|curl -fsSL https://raw.githubusercontent.com/common-repo/common-repo/main/install.sh | sh")
        else
          echo "✓ common-repo $(common-repo --version 2>/dev/null | head -1 || echo 'installed')"
        fi

        # Check prek
        if ! command -v prek &> /dev/null; then
          echo "⚠ prek (optional) - configuration management tool"
        else
          echo "✓ prek installed"
        fi

        # Check mcp-cli
        if ! command -v mcp &> /dev/null; then
          echo "⚠ mcp-cli (optional) - MCP server interface"
        else
          echo "✓ mcp-cli installed"
        fi

        # Report missing tools
        if [ ${#MISSING[@]} -ne 0 ]; then
          echo ""
          echo "❌ Missing required tools:"
          for entry in "${MISSING[@]}"; do
            tool="${entry%%|*}"
            install="${entry#*|}"
            echo "  - $tool"
            echo "    Install: $install"
          done
          echo ""
          echo "Run 'task install-tools' to auto-install missing tools (if supported)"
          echo "Or run 'task bootstrap' to install Go-based tools only"
          exit 1
        else
          echo ""
          echo "✅ All required tools are installed!"
        fi

  install-tools:
    desc: Install missing required tools and pre-commit hooks automatically
    cmds:
      - |
        echo "Installing missing tools..."
        HAS_BREW=false
        INSTALLED=()
        FAILED=()

        # Check if brew is available
        if command -v brew &> /dev/null; then
          HAS_BREW=true
          echo "✓ Homebrew detected"
        else
          echo "⚠ Homebrew not found - limited auto-install support"
        fi

        # Install Go
        if ! command -v go &> /dev/null; then
          echo "Installing Go..."
          if [ "$HAS_BREW" = true ]; then
            if brew install go; then
              INSTALLED+=("go")
            else
              FAILED+=("go")
            fi
          else
            echo "  ❌ Cannot auto-install Go without Homebrew"
            echo "  → Install from: https://go.dev/doc/install"
            FAILED+=("go")
          fi
        fi

        # Install golangci-lint (requires Go)
        if ! command -v golangci-lint &> /dev/null; then
          if command -v go &> /dev/null; then
            echo "Installing golangci-lint..."
            if go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest; then
              INSTALLED+=("golangci-lint")
            else
              FAILED+=("golangci-lint")
            fi
          else
            echo "  ⚠ Skipping golangci-lint (Go not available)"
            FAILED+=("golangci-lint")
          fi
        fi

        # Install bd (beads)
        if ! command -v bd &> /dev/null; then
          echo "Installing bd (beads)..."
          if [ "$HAS_BREW" = true ]; then
            if brew install steveyegge/beads/bd; then
              INSTALLED+=("bd")
            else
              FAILED+=("bd")
            fi
          else
            echo "  Attempting install via curl..."
            if curl -fsSL https://raw.githubusercontent.com/steveyegge/beads/main/scripts/install.sh | bash; then
              INSTALLED+=("bd")
            else
              FAILED+=("bd")
            fi
          fi
        fi

        # Install pre-commit
        if ! command -v pre-commit &> /dev/null; then
          echo "Installing pre-commit..."
          if [ "$HAS_BREW" = true ]; then
            if brew install pre-commit; then
              INSTALLED+=("pre-commit")
            else
              FAILED+=("pre-commit")
            fi
          else
            echo "  ❌ Cannot auto-install pre-commit without Homebrew or pip"
            echo "  → Install from: https://pre-commit.com/#install"
            FAILED+=("pre-commit")
          fi
        fi

        # Install common-repo
        if ! command -v common-repo &> /dev/null; then
          echo "Installing common-repo..."
          if curl -fsSL https://raw.githubusercontent.com/common-repo/common-repo/main/install.sh | sh; then
            # Add to PATH for current session
            export PATH="$HOME/.local/bin:$PATH"
            INSTALLED+=("common-repo")
          else
            echo "  ❌ Failed to install common-repo"
            FAILED+=("common-repo")
          fi
        fi

        # Summary
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        if [ ${#INSTALLED[@]} -gt 0 ]; then
          echo "✅ Successfully installed:"
          for tool in "${INSTALLED[@]}"; do
            echo "  - $tool"
          done
        fi

        if [ ${#FAILED[@]} -gt 0 ]; then
          echo "❌ Failed to install:"
          for tool in "${FAILED[@]}"; do
            echo "  - $tool"
          done
          echo ""
          echo "Run 'task check-tools' to see installation instructions"
          exit 1
        fi

        echo ""
        echo "✅ All tools installed successfully!"

        # Install pre-commit hooks if pre-commit is available
        if command -v pre-commit &> /dev/null; then
          echo ""
          echo "Installing pre-commit hooks..."
          if command -v prek &> /dev/null; then
            if prek install; then
              echo "✅ Pre-commit hooks installed via prek"
            else
              echo "⚠ prek install failed, trying pre-commit install"
              if pre-commit install; then
                echo "✅ Pre-commit hooks installed"
              else
                echo "⚠ Failed to install pre-commit hooks"
              fi
            fi
          else
            if pre-commit install; then
              echo "✅ Pre-commit hooks installed"
            else
              echo "⚠ Failed to install pre-commit hooks"
            fi
          fi
        fi

        echo ""
        echo "Run 'task check-tools' to verify your setup"

  bootstrap:
    desc: Bootstrap and set up dependencies and tools
    cmds:
      - task install-tools
      - echo "Installing Go dependencies..."
      - go mod download
      - go mod verify
      - echo "Bootstrap complete!"

  deps:
    desc: Download and verify Go module dependencies
    cmds:
      - go mod download
      - go mod verify

  build:
    desc: Build the binary
    deps: [deps]
    cmds:
      - echo "Building binary..."
      - mkdir -p "{{.BUILD_DIR}}"
      - go build -o "{{.BUILD_DIR}}/{{.BINARY_NAME}}" ./cmd/lazycfg
      - echo "Built successfully - {{.BUILD_DIR}}/{{.BINARY_NAME}}"

  fmt:
    desc: Format Go code
    cmds:
      - echo "Formatting Go code..."
      - go fmt ./...
      - echo "Formatting complete!"

  lint:
    desc: Run linters
    cmds:
      - echo "Running golangci-lint..."
      - golangci-lint run ./...
      - echo "Linting complete!"

  test:
    desc: Run tests
    cmds:
      - echo "Running tests..."
      - go test ./... -v
      - echo "Tests complete!"

  test-coverage:
    desc: Run tests with coverage report
    cmds:
      - echo "Running tests with coverage..."
      - go test ./... -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  check:
    desc: Run fmt, lint, and test
    cmds:
      - task fmt
      - task lint
      - task test

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "Cleaning build artifacts..."
      - rm -rf "{{.BUILD_DIR}}"
      - rm -f coverage.out coverage.html
      - echo "Clean complete!"

  install:
    desc: Install the binary to GOPATH/bin
    deps: [build]
    cmds:
      - echo "Installing binary..."
      - go install ./cmd/lazycfg
      - echo "Installed successfully!"

  dev:
    desc: Build and run the binary
    deps: [build]
    cmds:
      - '"{{.BUILD_DIR}}/{{.BINARY_NAME}}" {{.CLI_ARGS}}'
