package aws

import "testing"

const testProfilePrefix = "sso_"

const generatedHeader = "# This file was generated by cfgctl. Do not edit manually.\n\n" +
	"[default]\n" +
	"region = us-east-1\n" +
	"output = json\n\n"

func TestBuildConfigContent(t *testing.T) {
	cfg := DefaultConfig()
	cfg.ProfilePrefix = testProfilePrefix
	cfg.SSO.Region = testRegion
	cfg.SSO.RegistrationScopes = defaultSSOScopes
	cfg.SSO.SessionName = defaultSSOSessionName
	cfg.SSO.StartURL = testStartURL

	profiles := []DiscoveredProfile{
		{
			AccountID:   "111111111111",
			AccountName: "prod",
			RoleName:    "Admin",
		},
		{
			AccountID:   "111111111111",
			AccountName: "prod",
			RoleName:    "ReadOnly",
		},
	}

	content, warnings, err := BuildConfigContent(cfg, profiles)
	if err != nil {
		t.Fatalf("BuildConfigContent failed: %v", err)
	}
	if len(warnings) != 0 {
		t.Fatalf("expected no warnings, got %v", warnings)
	}

	expected := generatedHeader + `[sso-session cfgctl]
sso_start_url = https://example.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access

[profile sso_prod/admin]
sso_session = cfgctl
sso_account_id = 111111111111
sso_account_name = prod
sso_role_name = Admin
sso_auto_populated = true

[profile sso_prod/readonly]
sso_session = cfgctl
sso_account_id = 111111111111
sso_account_name = prod
sso_role_name = ReadOnly
sso_auto_populated = true`

	if content != expected {
		t.Fatalf("config content = %q", content)
	}
}

func TestBuildConfigContentCredentialProcess(t *testing.T) {
	cfg := DefaultConfig()
	cfg.ProfilePrefix = testProfilePrefix
	cfg.SSO.Region = testRegion
	cfg.SSO.RegistrationScopes = defaultSSOScopes
	cfg.SSO.SessionName = defaultSSOSessionName
	cfg.SSO.StartURL = testStartURL
	cfg.UseCredentialProcess = true

	profiles := []DiscoveredProfile{
		{
			AccountID:   "111111111111",
			AccountName: "prod",
			RoleName:    "Admin",
		},
	}

	content, warnings, err := BuildConfigContent(cfg, profiles)
	if err != nil {
		t.Fatalf("BuildConfigContent failed: %v", err)
	}
	if len(warnings) != 0 {
		t.Fatalf("expected no warnings, got %v", warnings)
	}

	expected := generatedHeader + `[sso-session cfgctl]
sso_start_url = https://example.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access

[profile sso_prod/admin]
credential_process = granted credential-process --profile sso_prod/admin
sso_auto_populated = true`

	if content != expected {
		t.Fatalf("config content = %q", content)
	}
}

func TestBuildCredentialProcessContent(t *testing.T) {
	cfg := DefaultConfig()
	cfg.ProfilePrefix = testProfilePrefix
	cfg.SSO.Region = testRegion
	cfg.SSO.RegistrationScopes = defaultSSOScopes
	cfg.SSO.SessionName = defaultSSOSessionName
	cfg.SSO.StartURL = testStartURL
	cfg.RoleChains = []RoleChain{
		{
			Name:          "prod-readonly",
			RoleARN:       "arn:aws:iam::111111111111:role/ReadOnly",
			SourceProfile: "sso_prod/admin",
		},
	}

	profiles := []DiscoveredProfile{
		{
			AccountID:   "111111111111",
			AccountName: "prod",
			RoleName:    "Admin",
		},
	}

	content, generatedNames, warnings, err := BuildCredentialProcessContent(cfg, profiles)
	if err != nil {
		t.Fatalf("BuildCredentialProcessContent failed: %v", err)
	}
	if len(warnings) != 0 {
		t.Fatalf("expected no warnings, got %v", warnings)
	}
	if len(generatedNames) != 2 {
		t.Fatalf("expected 2 generated names, got %v", generatedNames)
	}

	expected := `[sso_prod/admin]
credential_process = granted credential-process --profile sso_prod/admin

[sso_prod-readonly]
credential_process = granted credential-process --profile sso_prod-readonly`

	if content != expected {
		t.Fatalf("credential content = %q", content)
	}
}

func TestBuildConfigContentTemplateAliases(t *testing.T) {
	cfg := DefaultConfig()
	cfg.ProfileTemplate = "{{ .account }}-{{ .role }}"
	cfg.SSO.Region = testRegion
	cfg.SSO.StartURL = testStartURL

	profiles := []DiscoveredProfile{
		{
			AccountID:   "123456789012",
			AccountName: "prod-account",
			RoleName:    "AdminAccess",
		},
	}

	content, _, err := BuildConfigContent(cfg, profiles)
	if err != nil {
		t.Fatalf("BuildConfigContent failed: %v", err)
	}

	expected := generatedHeader + `[sso-session cfgctl]
sso_start_url = https://example.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access

[profile prod-account-adminaccess]
sso_session = cfgctl
sso_account_id = 123456789012
sso_account_name = prod-account
sso_role_name = AdminAccess
sso_auto_populated = true`

	if content != expected {
		t.Fatalf("config content = %q", content)
	}
}

func TestBuildConfigContentOverwritesOnCollision(t *testing.T) {
	cfg := DefaultConfig()
	cfg.ProfileTemplate = "{{ .AccountName }}-{{ .RoleName }}"
	cfg.SSO.Region = testRegion
	cfg.SSO.StartURL = testStartURL

	profiles := []DiscoveredProfile{
		{
			AccountID:   "111111111111",
			AccountName: "prod",
			RoleName:    "Admin",
		},
		{
			AccountID:   "999999999999",
			AccountName: "prod",
			RoleName:    "Admin",
		},
	}

	content, _, err := BuildConfigContent(cfg, profiles)
	if err != nil {
		t.Fatalf("BuildConfigContent failed: %v", err)
	}

	expected := generatedHeader + `[sso-session cfgctl]
sso_start_url = https://example.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access

[profile prod-admin]
sso_session = cfgctl
sso_account_id = 999999999999
sso_account_name = prod
sso_role_name = Admin
sso_auto_populated = true`

	if content != expected {
		t.Fatalf("config content = %q", content)
	}
}

func TestBuildConfigContentErrorsOnEmptySessionName(t *testing.T) {
	cfg := DefaultConfig()
	cfg.SSO.Region = testRegion
	cfg.SSO.StartURL = testStartURL
	cfg.SSO.SessionName = ""

	_, _, err := BuildConfigContent(cfg, nil)
	if err == nil {
		t.Fatal("expected error for empty session name")
	}
}

func TestBuildConfigContentErrorsOnEmptyTemplate(t *testing.T) {
	cfg := DefaultConfig()
	cfg.ProfileTemplate = ""
	cfg.SSO.Region = testRegion
	cfg.SSO.StartURL = testStartURL

	_, _, err := BuildConfigContent(cfg, nil)
	if err == nil {
		t.Fatal("expected error for empty template")
	}
}

func TestBuildConfigContentRoleChains(t *testing.T) {
	cfg := DefaultConfig()
	cfg.ProfilePrefix = testProfilePrefix
	cfg.SSO.Region = testRegion
	cfg.SSO.RegistrationScopes = defaultSSOScopes
	cfg.SSO.SessionName = defaultSSOSessionName
	cfg.SSO.StartURL = testStartURL
	cfg.RoleChains = []RoleChain{
		{
			Name:          "prod-readonly",
			RoleARN:       "arn:aws:iam::111111111111:role/ReadOnly",
			SourceProfile: "sso_prod/admin",
		},
		{
			Name:          "staging-deploy",
			Region:        "us-west-2",
			RoleARN:       "arn:aws:iam::222222222222:role/DeployRole",
			SourceProfile: "sso_staging/poweruser",
		},
	}

	profiles := []DiscoveredProfile{
		{
			AccountID:   "111111111111",
			AccountName: "prod",
			RoleName:    "Admin",
		},
		{
			AccountID:   "222222222222",
			AccountName: "staging",
			RoleName:    "PowerUser",
		},
	}

	content, warnings, err := BuildConfigContent(cfg, profiles)
	if err != nil {
		t.Fatalf("BuildConfigContent failed: %v", err)
	}
	if len(warnings) != 0 {
		t.Fatalf("expected no warnings, got %v", warnings)
	}

	expected := generatedHeader + `[sso-session cfgctl]
sso_start_url = https://example.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access

[profile sso_prod/admin]
sso_session = cfgctl
sso_account_id = 111111111111
sso_account_name = prod
sso_role_name = Admin
sso_auto_populated = true

[profile sso_staging/poweruser]
sso_session = cfgctl
sso_account_id = 222222222222
sso_account_name = staging
sso_role_name = PowerUser
sso_auto_populated = true

[profile sso_prod-readonly]
source_profile = sso_prod/admin
role_arn = arn:aws:iam::111111111111:role/ReadOnly
sso_auto_populated = true

[profile sso_staging-deploy]
source_profile = sso_staging/poweruser
role_arn = arn:aws:iam::222222222222:role/DeployRole
region = us-west-2
sso_auto_populated = true`

	if content != expected {
		t.Fatalf("config content = %q", content)
	}
}

func TestBuildConfigContentRoleChainWarnings(t *testing.T) {
	cfg := DefaultConfig()
	cfg.ProfilePrefix = testProfilePrefix
	cfg.SSO.Region = testRegion
	cfg.SSO.RegistrationScopes = defaultSSOScopes
	cfg.SSO.SessionName = defaultSSOSessionName
	cfg.SSO.StartURL = testStartURL
	cfg.RoleChains = []RoleChain{
		{
			Name:          "prod-readonly",
			RoleARN:       "arn:aws:iam::111111111111:role/ReadOnly",
			SourceProfile: "sso_prod/admin",
		},
	}

	profiles := []DiscoveredProfile{}

	_, warnings, err := BuildConfigContent(cfg, profiles)
	if err != nil {
		t.Fatalf("BuildConfigContent failed: %v", err)
	}
	if len(warnings) != 1 {
		t.Fatalf("expected 1 warning, got %v", warnings)
	}
}
