// Package aws provides AWS configuration management.
package aws

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/jmreicha/lazycfg/internal/core"
)

// ProviderName is the unique identifier for the AWS provider.
const ProviderName = "aws"

var errProviderConfigNil = errors.New("aws provider configuration is nil")

// Provider implements the core.Provider interface for AWS configuration management.
type Provider struct {
	config *Config
}

// NewProvider creates a new AWS provider instance with the given configuration.
func NewProvider(config *Config) *Provider {
	if config == nil {
		config = DefaultConfig()
	}

	return &Provider{
		config: config,
	}
}

// Name returns the unique identifier for this provider.
func (p *Provider) Name() string {
	return ProviderName
}

// Validate checks if all prerequisites for this provider are met.
func (p *Provider) Validate(_ context.Context) error {
	if p.config == nil {
		return errProviderConfigNil
	}

	if !p.config.Enabled {
		return nil
	}

	return p.config.Validate()
}

// Generate creates the configuration files for this provider.
func (p *Provider) Generate(ctx context.Context, opts *core.GenerateOptions) (*core.Result, error) {
	result := &core.Result{
		Provider:     p.Name(),
		FilesCreated: []string{},
		FilesSkipped: []string{},
		Warnings:     []string{},
		Metadata:     make(map[string]interface{}),
	}

	if p.config == nil {
		return nil, errProviderConfigNil
	}

	if opts != nil && opts.Config != nil {
		cfg, ok := opts.Config.(*Config)
		if !ok {
			return nil, errors.New("aws config has unexpected type")
		}
		p.config = cfg
	}

	if err := p.config.Validate(); err != nil {
		return nil, err
	}

	if !p.config.Enabled {
		result.Warnings = append(result.Warnings, "aws provider is disabled")
		return result, nil
	}

	outputPath := p.config.ConfigPath

	if _, err := os.Stat(outputPath); err == nil && opts != nil && !opts.Force && !opts.DryRun {
		result.FilesSkipped = append(result.FilesSkipped, outputPath)
		result.Warnings = append(result.Warnings, "config file exists, use --force to overwrite")
		return result, nil
	}

	profiles, err := DiscoverProfiles(ctx, p.config, nil)
	if err != nil {
		return nil, err
	}

	configContent, warnings, err := BuildConfigContent(p.config, profiles)
	if err != nil {
		return nil, err
	}
	result.Warnings = append(result.Warnings, warnings...)

	if opts != nil && opts.DryRun {
		result.Warnings = append(result.Warnings, "dry-run mode: no files were actually created")
		result.Metadata["config_path"] = outputPath
		result.Metadata["config_content"] = configContent
		return result, nil
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0700); err != nil {
		return nil, fmt.Errorf("failed to create config directory: %w", err)
	}

	if err := os.WriteFile(outputPath, []byte(configContent), 0600); err != nil {
		return nil, fmt.Errorf("failed to write config file: %w", err)
	}

	result.FilesCreated = append(result.FilesCreated, outputPath)
	result.Metadata["discovered_profiles"] = len(profiles)

	return result, nil
}

// Backup creates a backup of existing configuration files.
func (p *Provider) Backup(_ context.Context) (string, error) {
	return "", nil
}

// Restore recovers configuration from a backup.
func (p *Provider) Restore(_ context.Context, _ string) error {
	return errors.New("restore not yet implemented for aws provider")
}

// Clean removes all configuration files generated by this provider.
func (p *Provider) Clean(_ context.Context) error {
	if p.config == nil {
		return errProviderConfigNil
	}

	if p.config.ConfigPath == "" {
		return nil
	}

	path, err := normalizeConfigPath(p.config.ConfigPath)
	if err != nil {
		return err
	}

	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("remove aws config: %w", err)
	}

	return nil
}
