# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfgctl" do
  name "cfgctl"
  desc "CLI for managing complex configuration setup"
  homepage "https://github.com/jmreicha/cfgctl"
  version "0.4.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfgctl"

  on_macos do
    on_intel do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "7c4d54b66fa3e5f3b342effda9ae1ff3053edf086218c613df1018f3ab09c2bd"
    end
    on_arm do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "eb9cec642270c06a31fe483878ee2baf8e9ac35557ef0d95cc64e402c72929b7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "2ccf45626b87b07b64729f48146b9e4774fc395e09302eb30c98bce5a9c88f25"
    end
    on_arm do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "da8ec2d2ee62079db152d42dd4ae9a1920ede30c0291335564d569ca5b7d8055"
    end
  end

  # No zap stanza required
end
