# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfgctl" do
  name "cfgctl"
  desc "CLI for managing complex configuration setup"
  homepage "https://github.com/jmreicha/cfgctl"
  version "0.4.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfgctl"

  on_macos do
    on_intel do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "1ffa81f6701f07f1e5400399c60830f7cf3a7ecc47c9b072f39d0e7a19264344"
    end
    on_arm do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "cc06f1f490732eb6e40301016fe90699f393a7fe3130f72075701bc0e57d0048"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "4a015f6efed4c82b76560ca694e2d391aaa48a55595fa863d2abf6a92e7e8a81"
    end
    on_arm do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "0e5c070e03bd4fb820291ca6980266c20ae8c10f55fab6900bc63e6bb3cd22a1"
    end
  end

  # No zap stanza required
end
