// Package cli provides the command-line interface for cfgctl.
package cli

import (
	"context"
	"errors"
	"fmt"

	"github.com/spf13/cobra"
)

func newCleanCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "clean [provider...]",
		Short: "Clean up generated configuration files",
		Long: `Remove configuration files generated by one or more providers.

Examples:
  cfgctl clean aws
  cfgctl clean aws kubernetes`,
		RunE: func(_ *cobra.Command, args []string) error {
			if len(args) == 0 {
				return errors.New("must specify at least one provider to clean")
			}

			ctx := context.Background()

			for _, providerName := range args {
				if err := engine.CleanProvider(ctx, providerName); err != nil {
					return fmt.Errorf("failed to clean %s: %w", providerName, err)
				}
				fmt.Printf("Cleaned: %s\n", providerName)
			}

			return nil
		},
	}

	return cmd
}
