// Package kubernetes provides a Kubernetes configuration provider implementation.
package kubernetes

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/jmreicha/lazycfg/internal/core"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/tools/clientcmd/api"
)

// ProviderName is the unique identifier for the Kubernetes provider.
const ProviderName = "kubernetes"

var errProviderConfigNil = errors.New("kubernetes provider configuration is nil")

// Provider implements the core.Provider interface for Kubernetes configuration management.
type Provider struct {
	config *Config
}

// NewProvider creates a new Kubernetes provider instance with the given configuration.
func NewProvider(config *Config) *Provider {
	if config == nil {
		config = DefaultConfig()
	}

	return &Provider{config: config}
}

// Name returns the unique identifier for this provider.
func (p *Provider) Name() string {
	return ProviderName
}

// Validate checks if all prerequisites for this provider are met.
func (p *Provider) Validate(_ context.Context) error {
	if p.config == nil {
		return errProviderConfigNil
	}

	if !p.config.Enabled {
		return nil
	}

	return p.config.Validate()
}

// Generate creates the configuration files for this provider.
func (p *Provider) Generate(ctx context.Context, opts *core.GenerateOptions) (*core.Result, error) {
	result := &core.Result{
		Provider:     p.Name(),
		FilesCreated: []string{},
		FilesSkipped: []string{},
		Warnings:     []string{},
		Metadata:     make(map[string]interface{}),
	}

	if p.config == nil {
		return nil, errProviderConfigNil
	}

	if opts != nil && opts.Config != nil {
		cfg, ok := opts.Config.(*Config)
		if !ok {
			return nil, errors.New("kubernetes config has unexpected type")
		}
		p.config = cfg
	}

	if err := p.config.Validate(); err != nil {
		return nil, err
	}

	if !p.config.Enabled {
		result.Warnings = append(result.Warnings, "kubernetes provider is disabled")
		return result, nil
	}

	outputPath := p.config.ConfigPath
	if outputPath == "" {
		return nil, errors.New("kubernetes config path is empty")
	}

	var discovered []DiscoveredCluster
	var err error

	if !p.config.MergeOnly {
		if p.config.Demo {
			discovered = demoClusters()
		} else {
			discovered, err = DiscoverEKSClusters(ctx, p.config, nil)
			if err != nil {
				return nil, err
			}
		}
	}

	var discoveredConfig *api.Config
	if len(discovered) > 0 {
		discoveredConfig, err = BuildKubeconfig(discovered, p.config.NamingPattern)
		if err != nil {
			return nil, err
		}
	}

	var mergeConfig *api.Config
	var mergeFiles []string
	if p.config.MergeEnabled || p.config.MergeOnly {
		mergeConfig, mergeFiles, err = MergeKubeconfigs(outputPath, p.config.Merge, discoveredConfig)
		if err != nil {
			return nil, err
		}
	} else {
		mergeConfig = discoveredConfig
	}

	if mergeConfig == nil {
		result.Warnings = append(result.Warnings, "no kubeconfig data generated")
		return result, nil
	}

	if len(mergeFiles) > 0 {
		result.Metadata["merge_files"] = mergeFiles
	}

	if opts != nil && opts.DryRun {
		result.Warnings = append(result.Warnings, "dry-run mode: no files were actually created")
		result.Metadata["discovered_clusters"] = len(discovered)
		result.Metadata["dry_run_output"] = outputPath
		if mergeConfig != nil {
			result.Metadata["dry_run_kubeconfig"] = mergeConfig
		}
		return result, nil
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0700); err != nil {
		return nil, fmt.Errorf("create kubeconfig directory: %w", err)
	}

	if err := clientcmd.WriteToFile(*mergeConfig, outputPath); err != nil {
		return nil, fmt.Errorf("write kubeconfig: %w", err)
	}

	result.FilesCreated = append(result.FilesCreated, outputPath)
	result.Metadata["discovered_clusters"] = len(discovered)
	return result, nil
}

// Backup creates a backup of existing configuration files.
func (p *Provider) Backup(_ context.Context) (string, error) {
	return "", nil
}

// Restore recovers configuration from a backup.
func (p *Provider) Restore(_ context.Context, _ string) error {
	return errors.New("restore not yet implemented for kubernetes provider")
}

// Clean removes all configuration files generated by this provider.
func (p *Provider) Clean(_ context.Context) error {
	if p.config == nil {
		return errProviderConfigNil
	}

	if p.config.ConfigPath == "" {
		return nil
	}

	path := filepath.Clean(os.ExpandEnv(p.config.ConfigPath))
	if !filepath.IsAbs(path) {
		return fmt.Errorf("kubernetes config path must be absolute: %s", p.config.ConfigPath)
	}

	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("remove kubeconfig: %w", err)
	}

	return nil
}

func demoClusters() []DiscoveredCluster {
	return []DiscoveredCluster{
		{
			Profile:  "demo",
			Region:   "us-east-1",
			Name:     "demo-app",
			Endpoint: "https://demo-app.example.com",
			CAData:   []byte("demo-ca"),
		},
		{
			Profile:  "demo",
			Region:   "us-west-2",
			Name:     "demo-platform",
			Endpoint: "https://demo-platform.example.com",
			CAData:   []byte("demo-ca"),
		},
	}
}
