name: Pull Request

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  description:
    runs-on: ubuntu-latest
    steps:
      - name: Description
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const prBody = pr.body?.trim() || "";

            const placeholderRegex = /^###\s*Description of intended changes\s*[\r\n]+###\s*Links to related Jira tickets or other references\s*$/i;

            let message = null;

            // Capture common parts of messages
            const commonContent = [
              "",
              "- A clear explanation of **why** the changes are needed and any relevant Jira tickets or references",
              "",
              "This helps reviewers understand the purpose of the change and is required before this PR can be merged."
            ].join("\n");

            // Check if the PR body is empty or hasn't been updated
            if (prBody === "") {
              message = "🚫 **Description Is Missing**\n\nThis pull request does not include a description. Please add:" + commonContent;
            } else if (placeholderRegex.test(prBody)) {
              message = "🚫 **Placeholder Description Detected**\n\nYour PR description still contains the default template. Please update it with:" + commonContent;
            }

            if (message) {
              // Post a comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: message
              });

              // Fail the job to block merging
              core.setFailed("PR description is invalid (missing or placeholder text).");
            }
